name: Build libfive and Create Addon Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0.0

env:
  # Location of libfive source within the repository
  LIBFIVE_SOURCE_DIR: libfive_src
  # Build configuration
  CMAKE_BUILD_TYPE: Release

jobs:
  #=================================================
  # Job: Build libfive for Windows
  #=================================================
  build-windows:
    name: Build libfive (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout Repository (including libfive source)
        uses: actions/checkout@v4
        # If libfive_src is a submodule, uncomment the next line
        # submodules: 'recursive'

      - name: Setup vcpkg (for C++ dependencies)
        uses: lukka/run-vcpkg@v11
        with:
          # Install required dependencies using vcpkg
          vcpkgGitCommitId: 'a5e9e37f8a7e105e00367117d64fd96d14e369f9' # Use a known good commit ID for stability

      - name: Install libfive dependencies via vcpkg
        run: |
          echo "Installing dependencies..."
          vcpkg install eigen3 libpng zlib --triplet x64-windows
        shell: pwsh # Use PowerShell

      - name: Configure CMake for libfive
        run: |
          cmake -S ${{ env.LIBFIVE_SOURCE_DIR }} -B build `
            -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} `
            -DBUILD_SHARED_LIBS=ON `
            -DLIBFIVE_BUILD_STUDIO=OFF `
            -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install `
            -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake
        shell: pwsh

      - name: Build and Install libfive
        run: cmake --build build --config ${{ env.CMAKE_BUILD_TYPE }} --target install
        shell: pwsh

      - name: Prepare Windows Artifacts
        # We need libfive.dll, libfive-stdlib.dll, libpng16.dll, zlib1.dll
        # They should be in the install/bin directory after installation
        run: |
          mkdir -p ${{ github.workspace }}/artifact/src
          mkdir -p ${{ github.workspace }}/artifact/stdlib
          cp ${{ github.workspace }}/install/bin/libfive.dll ${{ github.workspace }}/artifact/src/
          cp ${{ github.workspace }}/install/bin/libfive-stdlib.dll ${{ github.workspace }}/artifact/stdlib/
          # Vcpkg usually puts dependency DLLs alongside the main ones
          cp ${{ github.workspace }}/install/bin/libpng16.dll ${{ github.workspace }}/artifact/src/
          cp ${{ github.workspace }}/install/bin/zlib1.dll ${{ github.workspace }}/artifact/src/
        shell: pwsh

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libfive-win
          path: ${{ github.workspace }}/artifact/ # Upload src and stdlib dirs

  #=================================================
  # Job: Build libfive for macOS
  #=================================================
  build-macos:
    name: Build libfive (macOS)
    runs-on: macos-latest # Use latest available macOS runner
    steps:
      - name: Checkout Repository (including libfive source)
        uses: actions/checkout@v4
        # If libfive_src is a submodule, uncomment the next line
        # submodules: 'recursive'

      - name: Install libfive dependencies via Homebrew
        run: brew install cmake eigen libpng

      - name: Configure CMake for libfive
        run: |
          cmake -S ${{ env.LIBFIVE_SOURCE_DIR }} -B build \
            -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} \
            -DBUILD_SHARED_LIBS=ON \
            -DLIBFIVE_BUILD_STUDIO=OFF \
            -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install \
            -DCMAKE_PREFIX_PATH=$(brew --prefix eigen);$(brew --prefix libpng) # Help CMake find brew libs

      - name: Build and Install libfive
        run: cmake --build build --config ${{ env.CMAKE_BUILD_TYPE }} --target install

      - name: Prepare macOS Artifacts
        # We need libfive.dylib, libfive-stdlib.dylib. Should be in install/lib
        run: |
          mkdir -p ${{ github.workspace }}/artifact/src
          mkdir -p ${{ github.workspace }}/artifact/stdlib
          cp ${{ github.workspace }}/install/lib/libfive.dylib ${{ github.workspace }}/artifact/src/
          cp ${{ github.workspace }}/install/lib/libfive-stdlib.dylib ${{ github.workspace }}/artifact/stdlib/
          # Dependencies like libpng are usually linked from the system via brew, no need to bundle

      - name: Upload macOS Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libfive-mac
          path: ${{ github.workspace }}/artifact/ # Upload src and stdlib dirs

  #=================================================
  # Job: Build libfive for Linux
  #=================================================
  build-linux:
    name: Build libfive (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository (including libfive source)
        uses: actions/checkout@v4
        # If libfive_src is a submodule, uncomment the next line
        # submodules: 'recursive'

      - name: Install libfive dependencies via apt
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libeigen3-dev libpng-dev zlib1g-dev

      - name: Configure CMake for libfive
        run: |
          cmake -S ${{ env.LIBFIVE_SOURCE_DIR }} -B build \
            -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} \
            -DBUILD_SHARED_LIBS=ON \
            -DLIBFIVE_BUILD_STUDIO=OFF \
            -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install

      - name: Build and Install libfive
        run: cmake --build build --config ${{ env.CMAKE_BUILD_TYPE }} --target install

      - name: Prepare Linux Artifacts
        # We need libfive.so, libfive-stdlib.so. Should be in install/lib
        run: |
          mkdir -p ${{ github.workspace }}/artifact/src
          mkdir -p ${{ github.workspace }}/artifact/stdlib
          cp ${{ github.workspace }}/install/lib/libfive.so ${{ github.workspace }}/artifact/src/
          cp ${{ github.workspace }}/install/lib/libfive-stdlib.so ${{ github.workspace }}/artifact/stdlib/
          # Dependencies like libpng/zlib are usually linked dynamically from system libs

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libfive-lin
          path: ${{ github.workspace }}/artifact/ # Upload src and stdlib dirs

  #=================================================
  # Job: Package Addon and Create Release
  #=================================================
  package-and-release:
    name: Package Addon and Release
    runs-on: ubuntu-latest
    # This job depends on all build jobs finishing successfully
    needs: [build-windows, build-macos, build-linux]

    steps:
      - name: Checkout Addon Code (Python parts)
        uses: actions/checkout@v4
        # No submodules needed here, just the addon Python code

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # --- Download Compiled Artifacts ---
      - name: Download Windows Artifacts
        uses: actions/download-artifact@v4
        with:
          name: libfive-win
          path: artifacts/win

      - name: Download macOS Artifacts
        uses: actions/download-artifact@v4
        with:
          name: libfive-mac
          path: artifacts/mac

      - name: Download Linux Artifacts
        uses: actions/download-artifact@v4
        with:
          name: libfive-lin
          path: artifacts/lin

      # --- Prepare Staging Directory ---
      - name: Create staging directory structure
        run: |
          mkdir -p staging/FieldForge
          # Create the structure expected by the addon
          mkdir -p staging/FieldForge/libfive/src
          mkdir -p staging/FieldForge/libfive/stdlib

      # --- Copy Files to Staging ---
      - name: Copy Addon Python files
        run: |
          cp __init__.py staging/FieldForge/
          # Copy the Python parts of the libfivepy wrapper
          cp libfive/__init__.py staging/FieldForge/libfive/
          cp libfive/ffi.py staging/FieldForge/libfive/
          cp libfive/runner.py staging/FieldForge/libfive/
          cp libfive/shape.py staging/FieldForge/libfive/
          cp libfive/stdlib/__init__.py staging/FieldForge/libfive/stdlib/
          cp libfive/stdlib/csg.py staging/FieldForge/libfive/stdlib/
          cp libfive/stdlib/shapes.py staging/FieldForge/libfive/stdlib/
          cp libfive/stdlib/text.py staging/FieldForge/libfive/stdlib/
          cp libfive/stdlib/transforms.py staging/FieldForge/libfive/stdlib/

      - name: Copy Compiled Windows Libraries
        run: |
          cp artifacts/win/src/* staging/FieldForge/libfive/src/
          cp artifacts/win/stdlib/* staging/FieldForge/libfive/stdlib/

      - name: Copy Compiled macOS Libraries
        run: |
          cp artifacts/mac/src/* staging/FieldForge/libfive/src/
          cp artifacts/mac/stdlib/* staging/FieldForge/libfive/stdlib/

      - name: Copy Compiled Linux Libraries
        run: |
          cp artifacts/lin/src/* staging/FieldForge/libfive/src/
          cp artifacts/lin/stdlib/* staging/FieldForge/libfive/stdlib/

      # --- Create Zip Archive ---
      - name: Create zip file
        run: |
          cd staging
          zip -r ../FieldForge-${{ env.VERSION }}.zip FieldForge/
          cd ..

      # --- Create GitHub Release ---
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: contains(github.ref_name, '-')
          files: FieldForge-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
